name: Deploy on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GOOGLE_CHAT_WEBHOOK: https://chat.googleapis.com/v1/spaces/AAQA-MJ2Cgg/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=1i-8OxHswcVbPOcCmPyYq7HzfoM9sOmpSSrDZPM4oZk
    steps:
      # Notify Deployment Started
      - name: Notify Deployment Started in Google Chat
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "🚀 Deployment started for PR #${{ github.event.pull_request.number }} in repository `${{ github.repository }}`."}' \
          $GOOGLE_CHAT_WEBHOOK

      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run Deployment Script
      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Add your deployment commands here, e.g., SSH to a server, run a script, etc.

      # Notify Deployment Completed
      - name: Notify Deployment Completed in Google Chat
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "✅ Deployment completed for PR #${{ github.event.pull_request.number }} in repository `${{ github.repository }}`."}' \
          $GOOGLE_CHAT_WEBHOOK
